"""Generate a fixed-seed planar SIRG as a TikZ figure.

Example (from the project root):
    python scripts/generate_sirg.py --dim 10 --intensity 1 --quantile "2*u - 1" --line-thickness 0.25 --line-opacity 0.35 --plain-background --kernel "np.exp(-(t / 2)**2)"

    python scripts/generate_sirg.py --dim 10 --vertex-process cox --intensity 1 --cox-function "1 + 0.8*np.sin(2*np.pi*x/period)*np.cos(2*np.pi*y/period)" --period 4 --kernel "np.exp(-t)"

    python scripts/generate_sirg.py --dim 10 --vertex-process mixed-binomial --count-quantile "np.where(u < .5, 100, 160)" --kernel "np.exp(-t)"
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

try:
    from .vertex_processes import (
        add_vertex_process_arguments,
        compile_quantile,
        evaluate_kernel,
        positive_float,
        positive_int,
        probability,
        quantile_values,
        sample_vertex_process,
    )
except ImportError:  # Direct execution: python scripts/generate_sirg.py
    from vertex_processes import (
        add_vertex_process_arguments,
        compile_quantile,
        evaluate_kernel,
        positive_float,
        positive_int,
        probability,
        quantile_values,
        sample_vertex_process,
    )


SEED = 42


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a spatial inhomogeneous random graph in [-dim, dim]^2."
    )
    parser.add_argument(
        "--dim",
        type=positive_int,
        required=True,
        help="Half-width of the square; e.g. 10 gives [-10,10]^2.",
    )
    add_vertex_process_arguments(
        parser,
        intensity_help="Base intensity per unit area.",
        cox_variables="x and y",
    )
    parser.add_argument(
        "--line-thickness",
        type=positive_float,
        default=0.4,
        help="Edge thickness in points (default: 0.4).",
    )
    parser.add_argument(
        "--line-opacity",
        type=probability,
        default=1.0,
        help="Edge opacity in [0, 1] (default: 1).",
    )
    parser.add_argument(
        "--plain-background",
        action="store_true",
        help="Omit the ambient grid and square border.",
    )
    parser.add_argument(
        "--random-seed",
        action="store_true",
        help="Use fresh system entropy instead of the fixed seed 42.",
    )
    parser.add_argument(
        "--quantile",
        type=str,
        default="2*u - 1",
        help='NumPy inverse-CDF expression in u (default: "2*u - 1").',
    )
    parser.add_argument(
        "--kernel",
        type=str,
        required=True,
        help='NumPy expression in t, w, and wp, e.g. "np.exp(-t)".',
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output TikZ path (default: figures/sirg.tex).",
    )
    return parser.parse_args()


def tikz_source(
    dim: int,
    points: np.ndarray,
    edges: np.ndarray,
    vertex_count: int,
    line_thickness: float,
    line_opacity: float,
    plain_background: bool,
    seed_label: str,
    process_description: str,
) -> str:
    scale = 3.5 / dim
    vertex_radius = 6.0 / dim
    lines = [
        f"\\begin{{tikzpicture}}[x={scale:.6g}cm, y={scale:.6g}cm]",
        (
            "% Generated by scripts/generate_sirg.py: "
            f"seed={seed_label}, vertices={vertex_count}, "
            f"process={process_description}, line width={line_thickness:g}pt, "
            f"opacity={line_opacity:g}"
        ),
    ]
    if not plain_background:
        lines.extend(
            [
                "% Ambient window",
                "\\draw[step=1, very thin, gray!25]",
                f"    (-{dim},-{dim}) grid ({dim},{dim});",
                "\\draw[thin, gray!70]",
                f"    (-{dim},-{dim}) rectangle ({dim},{dim});",
            ]
        )
    lines.extend(["", "% Vertices"])

    lines.extend(
        f"\\coordinate (v{i}) at ({x:.8g},{y:.8g});"
        for i, (x, y) in enumerate(points)
    )
    lines.extend(["", "% Edges"])
    lines.extend(
        (
            f"\\draw[line width={line_thickness:.6g}pt, "
            f"opacity={line_opacity:.6g}] (v{i}) -- (v{j});"
        )
        for i, j in edges
    )
    lines.extend(["", "% Vertices"])
    if vertex_count:
        vertex_names = ",".join(f"v{i}" for i in range(vertex_count))
        lines.extend(
            [
                f"\\foreach \\v in {{{vertex_names}}} {{",
                f"    \\fill (\\v) circle ({vertex_radius:.6g}pt);",
                "}",
            ]
        )
    lines.extend(["\\end{tikzpicture}", ""])
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    seed = None if args.random_seed else SEED
    rng = np.random.default_rng(seed)

    try:
        vertex_sample = sample_vertex_process(
            process=args.vertex_process,
            rng=rng,
            lower=(-args.dim, -args.dim),
            upper=(args.dim, args.dim),
            intensity=args.intensity,
            cox_function=args.cox_function,
            period=args.period,
            cox_bound=args.cox_bound,
            count_quantile=args.count_quantile,
            variables=("x", "y"),
        )
        points = vertex_sample.points
        vertex_count = len(points)
        quantile = compile_quantile(args.quantile)
        epsilon = np.finfo(float).eps
        uniforms = np.clip(rng.random(vertex_count), epsilon, 1.0 - epsilon)
        weights = quantile_values(quantile, uniforms)
    except ValueError as exc:
        raise SystemExit(f"error: {exc}") from exc

    first, second = np.triu_indices(vertex_count, k=1)
    distances = np.linalg.norm(points[first] - points[second], axis=1)
    try:
        probabilities = evaluate_kernel(
            args.kernel, distances, weights[first], weights[second]
        )
    except ValueError as exc:
        raise SystemExit(f"error: {exc}") from exc
    selected = rng.random(probabilities.size) < probabilities
    edges = np.column_stack((first[selected], second[selected]))

    output = args.output or (
        Path(__file__).resolve().parents[1] / "figures" / "sirg.tex"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        tikz_source(
            args.dim,
            points,
            edges,
            vertex_count,
            args.line_thickness,
            args.line_opacity,
            args.plain_background,
            "random" if args.random_seed else str(SEED),
            vertex_sample.description,
        ),
        encoding="utf-8",
    )
    print(
        f"Wrote {output} ({vertex_count} vertices, {len(edges)} edges, "
        f"process={vertex_sample.description})."
    )


if __name__ == "__main__":
    main()
